### ISSUE TITLE
It's not always possible to find out what the current input language is

### ISSUE THREAD

**Issue by estorski** [estorski/langlay#91]
1) run into a situation when a window appears and disappears from the screen quickly;

System.NullReferenceException: currentLayout must not be null
   at Product.OverlayService.LanguageCheckTimer_Tick(Object sender, EventArgs e)
   at System.Windows.Forms.Timer.OnTick(EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by estorski** [comment]
This also happens, if the currently active window is a command line prompt (cmd), especially if it has elevated permissions while the tool itself - does not.
